// Generated by CoffeeScript 1.4.0
(function() {
  var charm, hypnotoad, interval, _ref;

  hypnotoad = require('./hypnotoad.js');

  _ref = hypnotoad(process), charm = _ref[0], interval = _ref[1];

  charm.removeAllListeners('^C');

  charm.on('^C', function() {
    charm.background(0).write('\n');
    charm.reset();
    return process.exit();
  });

}).call(this);
