// Generated by CoffeeScript 1.4.0
(function() {
  var http, hypnotoad, server;

  http = require('http');

  hypnotoad = require('./hypnotoad.js');

  server = http.createServer(function(req, res) {
    var charm, interval, _ref;
    res.setHeader('content-type', 'text/ansi');
    _ref = hypnotoad(res), charm = _ref[0], interval = _ref[1];
    return req.connection.on('end', function() {
      clearInterval(interval);
      return charm.end();
    });
  });

  server.listen(8081);

  console.log('listening on localhost:8081');

}).call(this);
